/**
 * Bundled, stdlib-only demo agent. `between init` writes FAKE_AGENT_SOURCE verbatim to
 * `.between/agents/fake-agent.mjs`, which the default developer_command/reviewer_command
 * invoke. It stands in for real `claude`/`codex` so the embed is demoable with ZERO native
 * deps and no external CLIs.
 *
 * It MIRRORS two source-of-truth shapes exactly:
 *  - the signal id format from buildSignal()  -> `<role>-<cycle4>-<hash12>`
 *  - the Ack / ReviewRecord / VerifyRecord shapes the daemon validates and reads.
 *
 * The embedded script uses string concatenation (no backticks / no ${}) so it can live
 * safely inside this TS template literal and be bundled by tsup.
 */
export const FAKE_AGENT_SOURCE = `// Between bundled demo agent (generated by 'between init'). Stdlib-only.
import { readFileSync, writeFileSync, mkdirSync, renameSync } from 'node:fs'
import { join } from 'node:path'

const role = process.argv[2] === 'developer' ? 'developer' : 'reviewer'
const root = process.env.BETWEEN_ROOT || process.cwd()
const dir = join(root, '.between')

function pad(n) { return String(n).padStart(4, '0') }

function out(line) { process.stdout.write('[' + role + '] ' + line + '\\n') }

// review/verify records are written once: keep a valid record for this hash (the broker may have
// sealed it read-only), otherwise replace a missing/malformed one atomically
function isFinding(f, hash) { return !!f && typeof f.id === 'string' && f.id.length > 0 && (f.severity === 'blocking' || f.severity === 'non-blocking') && typeof f.summary === 'string' && f.target_hash === hash && (f.agent === undefined || (typeof f.agent === 'string' && f.agent.length > 0)) }
function isReview(r, hash, cycle) { return r.diff_hash === hash && r.cycle === cycle && Array.isArray(r.findings) && r.findings.every(function (f) { return isFinding(f, hash) }) && r.complete === true }
function isVerify(r, hash) { return r.diff_hash === hash && typeof r.passed === 'boolean' && (r.summary === undefined || typeof r.summary === 'string') }
function writeRecord(file, text, hash, cycle, valid) {
  try { const r = JSON.parse(readFileSync(file, 'utf8')); if (r && valid(r, hash, cycle)) return false } catch {}
  const tmp = file + '.' + process.pid + '.tmp'
  writeFileSync(tmp, text)
  renameSync(tmp, file)
  return true
}

function act() {
  let state
  try { state = JSON.parse(readFileSync(join(dir, 'state.json'), 'utf8')) } catch { out('no state yet'); return }
  const cycle = state.workflow && state.workflow.cycle
  const hash = state.diff && state.diff.hash
  if (typeof cycle !== 'number' || !hash) { out('no diff to act on'); return }
  const id = role + '-' + pad(cycle) + '-' + String(hash).slice(0, 12)
  mkdirSync(join(dir, 'acks'), { recursive: true })
  writeFileSync(join(dir, 'acks', id + '.json'), JSON.stringify({ signal_id: id, target: role, cycle: cycle, diff_hash: hash, acked_at: new Date().toISOString() }, null, 2))
  out('acked ' + id)
  if (role === 'reviewer') {
    const name = 'cycle-' + pad(cycle)
    mkdirSync(join(dir, 'reviews'), { recursive: true })
    mkdirSync(join(dir, 'verify'), { recursive: true })
    const wroteReview = writeRecord(join(dir, 'reviews', name + '.json'), JSON.stringify({ cycle: cycle, diff_hash: hash, findings: [], complete: true }, null, 2), hash, cycle, isReview)
    const wroteVerify = writeRecord(join(dir, 'verify', name + '.json'), JSON.stringify({ diff_hash: hash, passed: true, summary: 'fake-agent: no blocking findings' }, null, 2), hash, cycle, isVerify)
    out(wroteReview || wroteVerify ? 'wrote clean review + passing verify for ' + name : 'records for ' + name + ' already written')
  }
}

out('fake-agent online')
act()
process.stdin.on('data', () => act())
process.stdin.on('end', () => process.exit(0))
process.stdin.resume()
`
