/**
 * Bundled, stdlib-only demo agent. `between init` writes FAKE_AGENT_SOURCE verbatim to
 * `.between/agents/fake-agent.mjs`, which the default developer_command/reviewer_command
 * invoke. It stands in for real `claude`/`codex` so the embed is demoable with ZERO native
 * deps and no external CLIs.
 *
 * It MIRRORS two source-of-truth shapes exactly:
 *  - the signal id format from buildSignal()  -> `<role>-<cycle4>-<hash12>`
 *  - the Ack / ReviewRecord / VerifyRecord shapes the daemon validates and reads.
 *
 * The embedded script uses string concatenation (no backticks / no ${}) so it can live
 * safely inside this TS template literal and be bundled by tsup.
 */
export const FAKE_AGENT_SOURCE = `// Between bundled demo agent (generated by 'between init'). Stdlib-only.
import { readFileSync, writeFileSync, mkdirSync } from 'node:fs'
import { join } from 'node:path'

const role = process.argv[2] === 'developer' ? 'developer' : 'reviewer'
const root = process.env.BETWEEN_ROOT || process.cwd()
const dir = join(root, '.between')

function pad(n) { return String(n).padStart(4, '0') }

function out(line) { process.stdout.write('[' + role + '] ' + line + '\\n') }

function act() {
  let state
  try { state = JSON.parse(readFileSync(join(dir, 'state.json'), 'utf8')) } catch { out('no state yet'); return }
  const cycle = state.workflow && state.workflow.cycle
  const hash = state.diff && state.diff.hash
  if (typeof cycle !== 'number' || !hash) { out('no diff to act on'); return }
  const id = role + '-' + pad(cycle) + '-' + String(hash).slice(0, 12)
  mkdirSync(join(dir, 'acks'), { recursive: true })
  writeFileSync(join(dir, 'acks', id + '.json'), JSON.stringify({ signal_id: id, target: role, cycle: cycle, diff_hash: hash, acked_at: new Date().toISOString() }, null, 2))
  out('acked ' + id)
  if (role === 'reviewer') {
    const name = 'cycle-' + pad(cycle)
    mkdirSync(join(dir, 'reviews'), { recursive: true })
    mkdirSync(join(dir, 'verify'), { recursive: true })
    writeFileSync(join(dir, 'reviews', name + '.json'), JSON.stringify({ cycle: cycle, diff_hash: hash, findings: [], complete: true }, null, 2))
    writeFileSync(join(dir, 'verify', name + '.json'), JSON.stringify({ diff_hash: hash, passed: true, summary: 'fake-agent: no blocking findings' }, null, 2))
    out('wrote clean review + passing verify for ' + name)
  }
}

out('fake-agent online')
act()
process.stdin.on('data', () => act())
process.stdin.on('end', () => process.exit(0))
process.stdin.resume()
`
