/**
 * Wrapper scripts for REAL agent CLIs, written by `between init --agent claude|codex`.
 *
 * HONESTY: only the bundled fake-agent is verified end-to-end. These wrappers encode the
 * documented invocation (see docs/AGENT-CONTRACT.md) but require the CLI installed + an API
 * key, and the exact flags/prompt may need tuning for your CLI version. The wrapper feeds the
 * agent the Between contract (read the signal + sealed bundle; write the ack/review/verify files)
 * and spawns the CLI; the CLI's own file tools do the writing — Between never fakes it.
 *
 * Sources use string concatenation (no backticks / no ${}) so they live safely in this TS
 * template literal and are bundled by tsup.
 */

const CONTRACT_PROMPT = [
  'You are a Between agent. Your ROLE is passed as the first CLI arg (reviewer or developer).',
  'BETWEEN_ROOT points to the repository root that owns .between/ state and output files.',
  'Read BETWEEN_ROOT/.between/signals/<role>.json and BETWEEN_ROOT/.between/state.json.',
  'If role is REVIEWER: review the IMMUTABLE review bundle at the path in state.diff.bundle_path',
  '  (an A1 sealed review object: {bundle_id, diff_hash, diff:{tracked,trackedRaw,untracked}, repository, environment}).',
  '  Do NOT read `git diff HEAD` — the live worktree may have moved; the bundle is the review object.',
  '  Prefer BETWEEN_REVIEW_WORKTREE when present; it is a sealed read-only materialization of the bundle.',
  '  Review against bundle.diff_hash, which equals state.diff.hash.',
  'If role is DEVELOPER: read `git diff HEAD` and apply the reviewer feedback to the working tree (do NOT merge or deploy).',
  'Compute id = role + "-" + String(cycle).padStart(4,"0") + "-" + diff_hash.slice(0,12).',
  'Write BETWEEN_ROOT/.between/acks/<id>.json = {signal_id:id, target:role, cycle, diff_hash, acked_at:ISO}.',
  'If role is reviewer: also write BETWEEN_ROOT/.between/reviews/cycle-<cycle4>.json =',
  '  {cycle, diff_hash, findings:[{id,severity:"blocking"|"non-blocking",summary,agent:"reviewer",target_hash:diff_hash}], complete:true}',
  '  and BETWEEN_ROOT/.between/verify/cycle-<cycle4>.json = {diff_hash, passed:boolean, summary}.',
].join(' ')

function wrapper(cli: string, exampleCmd: string): string {
  return (
    "// Between real-agent wrapper (generated by 'between init'). Requires the '" +
    cli +
    "' CLI + an API key.\n" +
    '// It is a TEMPLATE: tune the spawn command/flags for your CLI version. Contract below.\n' +
    "import { spawnSync } from 'node:child_process'\n" +
    "import { readFileSync } from 'node:fs'\n" +
    "import { join } from 'node:path'\n\n" +
    "const role = process.argv[2] === 'developer' ? 'developer' : 'reviewer'\n" +
    'const root = process.env.BETWEEN_ROOT || process.cwd()\n' +
    "const reviewWorktree = process.env.BETWEEN_REVIEW_WORKTREE || ''\n" +
    "const agentCwd = role === 'reviewer' && reviewWorktree ? reviewWorktree : root\n" +
    "function read(p){ try { return readFileSync(join(root, '.between', p), 'utf8') } catch { return '' } }\n" +
    "const signal = read('signals/' + role + '.json')\n" +
    'const CONTRACT = ' +
    JSON.stringify(CONTRACT_PROMPT) +
    '\n' +
    "const prompt = CONTRACT + '\\n\\nYour role: ' + role + '\\nBETWEEN_ROOT: ' + root + '\\nBETWEEN_REVIEW_WORKTREE: ' + reviewWorktree + '\\nSignal:\\n' + signal\n" +
    '// Documented invocation (confidence: claude HIGH, codex MEDIUM — smoke-test before relying):\n' +
    '// ' +
    exampleCmd +
    '\n' +
    "const r = spawnSync('" +
    cli +
    "', " +
    spawnArgs(cli) +
    ", { cwd: agentCwd, input: prompt, stdio: ['pipe','inherit','inherit'] })\n" +
    "if (r.error && r.error.code === 'ENOENT') {\n" +
    "  process.stderr.write('[' + role + '] " +
    cli +
    ' CLI not found. Install it + set the API key, or edit ' +
    cli +
    "_command in .between/config.yaml.\\n')\n" +
    '  process.exit(1)\n' +
    '}\n' +
    'process.exit(r.status == null ? 1 : r.status)\n'
  )
}

function spawnArgs(cli: string): string {
  // claude: print mode reads the prompt from stdin; codex: non-interactive exec subcommand.
  return cli === 'claude'
    ? "['-p', '--output-format', 'text']"
    : "['exec', '--ask-for-approval', 'never']"
}

export const CLAUDE_AGENT_SOURCE = wrapper(
  'claude',
  'echo "<prompt>" | claude -p --output-format text   (needs ANTHROPIC_API_KEY)',
)

export const CODEX_AGENT_SOURCE = wrapper(
  'codex',
  'codex exec "<prompt>"   (needs OPENAI_API_KEY; verify --json/--output-schema for your version)',
)

export type { AgentPreset } from '../core/constants'
